version: "3.8"
services:
  backend:
    container_name: calc
    image: "andrei1999cj/calories-calculator:15.6.2023.15.44.32"
    environment:
      - SPRING_PROFILES_ACTIVE=amazon
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY_VALUE=${SECRET_KEY_VALUE}
      - DB_SERVER_NAME=${DB_SERVER_NAME}
      - DB_NAME=${DB_NAME}
    ports:
      - "80:8080"
    restart: "always"
