version: "3.8"
services:
  backend:
    container_name: calc
    image: "andrei1999cj/calories-calculator:15.6.2023.13.37.33"
    environment:
      - SPRING_PROFILES_ACTIVE=amazon
      - DB_USERNAME=andrei1999cj
      - DB_PASSWORD=Esobddsaopn32
      - SECRET_KEY_VALUE="5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437"
      - DB_SERVER_NAME=awseb-e-bxjc3fubeh-stack-awsebrdsdatabase-gxl7y7wuenne.c9ls5sjeztc7.us-east-1.rds.amazonaws.com
      - DB_NAME=${{secrets.DB_NAME}}
    ports:
      - "80:8080"
    restart: "always"
