version: "3.8"
services:
  backend:
      container_name: calc
      image: "andrei1999cj/calories-calculator:15.6.2023.11.45.40"
      environment:
        - SPRING_PROFILES_ACTIVE=amazon
        - DB_USERNAME=${{secrets.DB_USERNAME_PRODUCTION}}
        - DB_PASSWORD=${{secrets.DB_PASSWORD_PRODUCTION}}
        - SECRET_KEY_VALUE=${{secrets.SECRET_KEY_VALUE}}
        - DB_SERVER_NAME=${{secrets.DB_SERVER_NAME}}
        - DB_NAME=calories_calculator
      ports:
        - "80:8080"
      restart: "always"
