name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  POSTGRESQL_DB: calories_calculator
  POSTGRESQL_USER: cojand
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'oracle'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          mvn --no-transfer-progress clean package -P build-frontend -DDB_PASSWORD=${{secrets.DB_PASSWORD}} -DDB_USERNAME=cojand -DSECRET_KEY_VALUE=${{secrets.SECRET_KEY_VALUE}}